# Generated by Django 5.1.2 on 2024-10-11 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myflight', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Airport',
            new_name='Airports',
        ),
    ]
