# Generated by Django 5.1.2 on 2024-10-11 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myflight', '0002_rename_airport_airports'),
    ]

    operations = [
        migrations.AddField(
            model_name='airports',
            name='city',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='airports',
            name='code',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='flights',
            name='destination',
            field=models.ForeignKey(max_length=64, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='myflight.airports'),
        ),
        migrations.AddField(
            model_name='flights',
            name='duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='flights',
            name='origin',
            field=models.ForeignKey(max_length=64, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='myflight.airports'),
        ),
    ]
