# Generated by Django 5.1.2 on 2024-10-11 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myflight', '0003_airports_city_airports_code_flights_destination_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='flights',
            name='passengers',
            field=models.ManyToManyField(blank=True, related_name='flights', to='myflight.passenger'),
        ),
    ]
